import { Avatar, AvatarFallback } from '@/components/ui/avatar';
import { Badge } from '@/components/ui/badge';
import { Button } from '@/components/ui/button';
import { Dialog, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle } from '@/components/ui/dialog';
import type { AuthUser } from '@/lib/api';
import { roleLabel } from '@/lib/role-labels';

export function UserDetailDialog({ onOpenChange, user }: { onOpenChange: (open: boolean) => void; user: AuthUser | null }) {
  return <Dialog open={user !== null} onOpenChange={onOpenChange}><DialogContent className="sm:max-w-2xl"><DialogHeader><DialogTitle>Detalle de usuario</DialogTitle><DialogDescription>Cuenta, acceso operativo y estado actual.</DialogDescription></DialogHeader>{user ? <div className="flex flex-col gap-5"><div className="flex items-start gap-4 rounded-lg border bg-muted/40 p-4"><Avatar className="size-12"><AvatarFallback>{user.name.charAt(0).toUpperCase()}</AvatarFallback></Avatar><div className="min-w-0"><p className="break-words font-semibold">{user.name}</p><p className="break-all text-sm text-muted-foreground">{user.email}</p></div></div><dl className="grid gap-3 sm:grid-cols-2"><Detail label="Usuario de acceso"><span className="font-mono">{user.username}</span></Detail><Detail label="Estado"><Badge variant={user.active ? 'default' : 'secondary'}>{user.active ? 'Activo' : 'Inactivo'}</Badge></Detail><Detail label="Roles operativos" wide><div className="flex flex-wrap gap-2">{user.roles.length ? user.roles.map((role) => <Badge key={role} variant="secondary">{roleLabel(role)}</Badge>) : <span className="text-muted-foreground">Sin rol asignado</span>}</div></Detail><Detail label="Acceso efectivo" wide><p>{user.permissions.length} permiso{user.permissions.length === 1 ? '' : 's'} habilitado{user.permissions.length === 1 ? '' : 's'} por el servidor.</p>{user.must_change_password ? <p className="mt-2 font-medium text-warning-foreground">Debe cambiar su contraseña en el próximo ingreso.</p> : null}</Detail></dl></div> : null}<DialogFooter><Button variant="outline" onClick={() => onOpenChange(false)}>Cerrar</Button></DialogFooter></DialogContent></Dialog>;
}
function Detail({ label, wide = false, children }: { label: string; wide?: boolean; children: React.ReactNode }) { return <div className={wide ? 'rounded-lg border p-4 sm:col-span-2' : 'rounded-lg border p-4'}><dt className="text-xs font-medium text-muted-foreground">{label}</dt><dd className="mt-1 text-sm">{children}</dd></div>; }
