import { Col, Row, Statistic, Typography } from 'antd';
import { InstitutionalDataGrid, type InstitutionalColumn } from '@/design-system/ag-grid';
import { formatLempirasUI } from '@/lib/moneyCents';
import { formatDate } from '@/lib/format/formatDate';
import type { ExecutiveReport } from '@/lib/api';
type Props = { report: ExecutiveReport }; type Item = ExecutiveReport['pending_aging']['items'][number];
const columns: InstitutionalColumn<Item>[] = [{ field: 'invoice_number', headerName: '# Factura', priority: 'primary' }, { field: 'patient', headerName: 'Paciente', priority: 'primary', flex: 1 }, { field: 'issued_at', headerName: 'Emitida', priority: 'secondary', valueFormatter: ({ value }) => pendingDate(value) }, { field: 'age_days', headerName: 'Antigüedad', priority: 'secondary', valueFormatter: ({ value }) => `${value} d` }, { field: 'total', headerName: 'Total', priority: 'tertiary', valueFormatter: ({ value }) => formatLempirasUI(value) }, { field: 'balance_due', headerName: 'Saldo', priority: 'primary', valueFormatter: ({ value }) => formatLempirasUI(value) }];
export function PendingAgingPanel({ report }: Props) { const aging = report.pending_aging; const buckets = [['0_7_days', '0 a 7 días'], ['8_30_days', '8 a 30 días'], ['31_plus_days', '31 o más días']] as const; return <section className="border border-border p-4" aria-labelledby="pending-title"><Typography.Title id="pending-title" level={3}>Pendientes y antigüedad</Typography.Title><Typography.Paragraph>Facturas con saldo abierto, agrupadas por días desde la emisión.</Typography.Paragraph><Row gutter={12}>{buckets.map(([key, label]) => <Col xs={24} md={8} key={key}><Statistic title={label} value={aging[key].count} suffix={formatLempirasUI(aging[key].amount)} /></Col>)}</Row><InstitutionalDataGrid ariaLabel="Facturas pendientes" regionAriaLabel="Facturas pendientes" gridAriaLabel="Facturas pendientes por antigüedad" caption="Facturas pendientes por antigüedad" description="Las facturas con saldo abierto aparecerán aquí según su antigüedad." rows={aging.items} columns={columns} getRowId={(item) => `${item.invoice_number}-${item.issued_at}-${item.bucket}`} state={aging.items.length ? 'ready' : 'empty'} emptyMessage="Sin facturas pendientes" density="compact" /></section>; }
function pendingDate(value: unknown): string { const formatted = formatDate(String(value ?? '')); return formatted === '-' ? 'Fecha no disponible' : formatted; }
