<#
.SYNOPSIS
  Registers a Windows Scheduled Task that runs `php artisan schedule:run`
  every minute. This is the bare-metal equivalent of the scheduler sidecar
  in docker-compose.prod.yml and is needed for installs that do not use
  Docker.

.DESCRIPTION
  The scheduled task:
  - Runs every minute, indefinitely.
  - Executes `php artisan schedule:run` from the backend project root.
  - Logs stdout/stderr to backend/storage/logs/scheduler-task.log so
    failures are visible.
  - Starts as soon as possible (no manual trigger needed).
  - Runs whether the user is logged in or not, with highest privileges
    only if the operator chooses -RunAsSystem.

  Use -Uninstall to remove the task.

.PARAMETER ProjectRoot
  Absolute path to the project root (parent of backend/). Defaults to
  the parent of the scripts folder.

.PARAMETER RunAsSystem
  If set, the task runs as SYSTEM (no password needed, but the task
  cannot access user-mounted resources). Default is the current user.

.PARAMETER PhpPath
  Path to the php executable. Default: php on PATH.
#>
[CmdletBinding()]
param(
    [string] $ProjectRoot,
    [switch] $RunAsSystem,
    [switch] $Uninstall,
    [string] $PhpPath
)

$ErrorActionPreference = "Stop"

if (-not $ProjectRoot) {
    $ProjectRoot = (Resolve-Path (Join-Path $PSScriptRoot "..")).Path
}
$backendRoot = Join-Path $ProjectRoot "backend"
if (-not (Test-Path -LiteralPath $backendRoot)) {
    Write-Error "Backend folder not found: $backendRoot"
    exit 2
}

if (-not $PhpPath) {
    $phpCommand = Get-Command php -ErrorAction SilentlyContinue
    if ($null -eq $phpCommand) {
        Write-Error "php not found on PATH. Pass -PhpPath 'C:\path\to\php.exe'."
        exit 3
    }
    $PhpPath = $phpCommand.Source
}

$taskName = "SistemaCajaHospitalaria-Scheduler"
$logFile = Join-Path $backendRoot "storage\logs\scheduler-task.log"

if ($Uninstall) {
    $existing = Get-ScheduledTask -TaskName $taskName -ErrorAction SilentlyContinue
    if ($existing) {
        Unregister-ScheduledTask -TaskName $taskName -Confirm:$false
        Write-Host "Unregistered scheduled task: $taskName"
    } else {
        Write-Host "No task named '$taskName' to uninstall."
    }
    exit 0
}

$action = New-ScheduledTaskAction `
    -Execute $PhpPath `
    -Argument "artisan schedule:run" `
    -WorkingDirectory $backendRoot

$trigger = New-ScheduledTaskTrigger `
    -Once `
    -At (Get-Date).AddMinutes(1) `
    -RepetitionInterval (New-TimeSpan -Minutes 1) `
    -RepetitionDuration (New-TimeSpan -Days 3650)

$principal = if ($RunAsSystem) {
    New-ScheduledTaskPrincipal -UserId "SYSTEM" -LogonType ServiceAccount -RunLevel Highest
} else {
    $currentUser = [System.Security.Principal.WindowsIdentity]::GetCurrent().Name
    New-ScheduledTaskPrincipal -UserId $currentUser -LogonType Interactive
}

$settings = New-ScheduledTaskSettingsSet `
    -AllowStartIfOnBatteries `
    -DontStopIfGoingOnBatteries `
    -StartWhenAvailable `
    -ExecutionTimeLimit (New-TimeSpan -Minutes 2) `
    -RestartCount 3 `
    -RestartInterval (New-TimeSpan -Minutes 1)

# Ensure the log directory exists.
$logDir = Split-Path $logFile -Parent
if (-not (Test-Path -LiteralPath $logDir)) {
    New-Item -ItemType Directory -Path $logDir -Force | Out-Null
}

# Wrap with logging so failures are visible. schtasks does not redirect
# stdout/stderr to a file automatically, but the scheduled task engine
# can be configured with a per-action redirect on newer Windows builds.
# We use a small launcher .ps1 that the task invokes.
$launcher = Join-Path $backendRoot "storage\app\private\run-scheduler-tick.ps1"
$launcherDir = Split-Path $launcher -Parent
if (-not (Test-Path -LiteralPath $launcherDir)) {
    New-Item -ItemType Directory -Path $launcherDir -Force | Out-Null
}
$launcherContent = @"
# Auto-generated by scripts/register_scheduler_cron.ps1
# Runs one tick of the Laravel scheduler, records the heartbeat, and
# logs the result.
`$ErrorActionPreference = "Continue"
`$now = Get-Date -Format "yyyy-MM-dd HH:mm:ss"
try {
    `$output = & "$PhpPath" artisan schedule:run 2>&1
    `$exitCode = `$LASTEXITCODE
    if (`$exitCode -ne 0) {
        throw "php artisan schedule:run failed with exit code `$exitCode. `$output"
    }
    "[" + `$now + "] OK: `$output" | Out-File -LiteralPath "$logFile" -Append -Encoding ASCII
    `$null = & "$PhpPath" artisan hospital:scheduler-tick --result=ok 2>&1
    exit 0
} catch {
    `$msg = `$_.Exception.Message
    "[" + `$now + "] FAIL: `$msg" | Out-File -LiteralPath "$logFile" -Append -Encoding ASCII
    `$null = & "$PhpPath" artisan hospital:scheduler-tick --result=fail --message="`$msg" 2>&1
    exit 1
}
"@
Set-Content -LiteralPath $launcher -Value $launcherContent -NoNewline -Encoding ASCII

$action = New-ScheduledTaskAction `
    -Execute "powershell.exe" `
    -Argument "-NoProfile -ExecutionPolicy Bypass -File `"$launcher`"" `
    -WorkingDirectory $backendRoot

$existing = Get-ScheduledTask -TaskName $taskName -ErrorAction SilentlyContinue
if ($existing) {
    Set-ScheduledTask -TaskName $taskName -Action $action -Trigger $trigger -Principal $principal -Settings $settings | Out-Null
    Write-Host "Updated scheduled task: $taskName"
} else {
    Register-ScheduledTask -TaskName $taskName -Action $action -Trigger $trigger -Principal $principal -Settings $settings -Description "Runs `php artisan schedule:run` every minute to drive Laravel's scheduler (daily backups, audit-log prune, failed-jobs prune)." | Out-Null
    Write-Host "Registered scheduled task: $taskName"
}

Write-Host ""
Write-Host "Verification:"
Write-Host "  Get-ScheduledTask -TaskName $taskName"
Write-Host "  Get-ScheduledTaskInfo -TaskName $taskName"
Write-Host "Log file:"
Write-Host "  $logFile"
exit 0
