<?php

declare(strict_types=1);

namespace App\Actions\Reports;

use App\Models\Invoice;
use App\Models\Payment;
use Illuminate\Routing\Route;
use Illuminate\Routing\Router;

/**
 * Dumps the API surface as a small OpenAPI 3.1 document.
 *
 * The contract is hand-curated to match the route definitions
 * declared in routes/api.php. It is enough to power a future
 * Swagger UI and to keep a single source of truth for the
 * cashier endpoints, but it does not aim to replace the deeper
 * schema generated by tools like darkaonline/l5-swagger.
 */
class OpenApiExporter
{
    /**
     * @var array<string, array{
     *     summary: string,
     *     tags: list<string>,
     *     security: bool,
     *     parameters?: list<string>,
     *     required_parameters?: list<string>
     * }>
     */
    private const ENDPOINTS = [
        '/api/health' => [
            'summary' => 'Liveness probe for the LAN server',
            'tags' => ['system'],
            'security' => false,
        ],
        '/api/system/setup-status' => [
            'summary' => 'One-shot setup status for the operator wizard',
            'tags' => ['system'],
            'security' => false,
        ],
        '/api/system/status' => [
            'summary' => 'Detailed operational status (env, db, queue, evidence)',
            'tags' => ['system'],
            'security' => true,
        ],
        '/api/system/health' => [
            'summary' => 'Public health snapshot (db, queue, backups, storage, errors)',
            'tags' => ['system'],
            'security' => false,
        ],
        '/api/system/csp-report' => [
            'summary' => 'CSP violation report endpoint',
            'tags' => ['system'],
            'security' => false,
        ],
        '/api/settings/logo' => [
            'summary' => 'Read the institucional logo URL',
            'tags' => ['settings'],
            'security' => false,
        ],
        '/api/settings/branding' => [
            'summary' => 'Read the public fiscal branding (no auth)',
            'tags' => ['settings'],
            'security' => false,
        ],
        '/api/auth/login' => [
            'summary' => 'Start an authenticated session and seed the CSRF cookie',
            'tags' => ['auth'],
            'security' => false,
        ],
        '/api/auth/session' => [
            'summary' => 'Return the current session user (or null)',
            'tags' => ['auth'],
            'security' => false,
        ],
        '/api/auth/me' => [
            'summary' => 'Return the current authenticated user payload',
            'tags' => ['auth'],
            'security' => true,
        ],
        '/api/auth/logout' => [
            'summary' => 'Destroy the current session',
            'tags' => ['auth'],
            'security' => true,
        ],
        '/api/auth/change-password' => [
            'summary' => 'Change the current user password (mandatory on first login)',
            'tags' => ['auth'],
            'security' => true,
        ],
        '/api/invoices' => [
            'summary' => 'List and create invoices',
            'tags' => ['invoices'],
            'security' => true,
        ],
        '/api/cash-sessions/current' => [
            'summary' => 'Return the cashier active cash session or null',
            'tags' => ['cash'],
            'security' => true,
        ],
        '/api/backups' => [
            'summary' => 'List or request backups',
            'tags' => ['backups'],
            'security' => true,
        ],
        '/api/reports/dashboard' => [
            'summary' => 'Aggregated dashboard metrics for the cashier landing page',
            'tags' => ['reports'],
            'security' => true,
        ],
        '/api/reports/daily' => [
            'summary' => 'Daily financial facts separated by billed, collected, pending, partial and voided',
            'tags' => ['reports'],
            'security' => true,
            'parameters' => ['date'],
            'required_parameters' => [],
        ],
        '/api/reports/monthly' => [
            'summary' => 'Monthly financial facts and daily evolution',
            'tags' => ['reports'],
            'security' => true,
            'parameters' => ['month'],
            'required_parameters' => [],
        ],
        '/api/reports/income' => [
            'summary' => 'Date-range income report with payment, status, cashier, cash session, area and category filters',
            'tags' => ['reports'],
            'security' => true,
            'parameters' => ['date_from', 'date_to', 'cash_session_id', 'user_id', 'category_id', 'area_id', 'method', 'status'],
            'required_parameters' => ['date_from', 'date_to'],
        ],
        '/api/reports/categories' => [
            'summary' => 'Category breakdown using historical invoice item snapshots and report filters',
            'tags' => ['reports'],
            'security' => true,
            'parameters' => ['date_from', 'date_to', 'cash_session_id', 'user_id', 'category_id', 'area_id', 'method', 'status'],
            'required_parameters' => ['date_from', 'date_to'],
        ],
        '/api/reports/areas' => [
            'summary' => 'Area income breakdown using historical invoice item snapshots and report filters',
            'tags' => ['reports'],
            'security' => true,
            'parameters' => ['date_from', 'date_to', 'cash_session_id', 'user_id', 'category_id', 'area_id', 'method', 'status'],
            'required_parameters' => ['date_from', 'date_to'],
        ],
        '/api/reports/services' => [
            'summary' => 'Service sales breakdown using historical invoice item snapshots and report filters',
            'tags' => ['reports'],
            'security' => true,
            'parameters' => ['date_from', 'date_to', 'cash_session_id', 'user_id', 'category_id', 'method', 'status'],
            'required_parameters' => ['date_from', 'date_to'],
        ],
        '/api/reports/operations' => [
            'summary' => 'Operational audit report for voids, reprints, payment reversals, backups and cashiers',
            'tags' => ['reports'],
            'security' => true,
            'parameters' => ['date_from', 'date_to', 'cash_session_id', 'user_id', 'category_id', 'area_id', 'method', 'status'],
            'required_parameters' => ['date_from', 'date_to'],
        ],
        '/api/reports/export' => [
            'summary' => 'Excel export for date-range financial reports with applied filters',
            'tags' => ['reports'],
            'security' => true,
            'parameters' => ['date_from', 'date_to', 'cash_session_id', 'user_id', 'category_id', 'area_id', 'method', 'status'],
            'required_parameters' => ['date_from', 'date_to'],
        ],
        '/api/reports/pdf' => [
            'summary' => 'Daily or date-range PDF closure export with applied filters',
            'tags' => ['reports'],
            'security' => true,
            'parameters' => ['date', 'date_from', 'date_to', 'cash_session_id', 'user_id', 'category_id', 'area_id', 'method', 'status'],
            'required_parameters' => [],
        ],
        '/api/reports/cash-sessions/{cashSession}' => [
            'summary' => 'Cash session reconciliation with expected cash, counted cash, difference and payment methods',
            'tags' => ['reports'],
            'security' => true,
        ],
        '/api/admin/users' => [
            'summary' => 'List, create and manage users with Spatie roles',
            'tags' => ['admin'],
            'security' => true,
        ],
    ];

    /**
     * @return array<string, mixed>
     */
    public function document(Router $router): array
    {
        $paths = [];

        foreach ($router->getRoutes()->getRoutes() as $route) {
            $path = '/'.ltrim($route->uri(), '/');
            if (! str_starts_with($path, '/api/')) {
                continue;
            }

            $metadata = self::ENDPOINTS[$path] ?? null;
            if ($metadata === null) {
                continue;
            }

            $methods = array_values(array_filter(
                $route->methods(),
                static fn (string $method): bool => $method !== 'HEAD',
            ));

            $entry = [];
            foreach ($methods as $method) {
                $entry[strtolower($method)] = [
                    'summary' => $metadata['summary'],
                    'tags' => $metadata['tags'],
                    'security' => $metadata['security']
                        ? [['sanctum-session' => []]]
                        : [],
                    'responses' => [
                        '200' => ['description' => 'Successful response'],
                        '401' => ['description' => 'Session expired or missing'],
                        '403' => ['description' => 'Permission denied'],
                        '422' => ['description' => 'Validation error'],
                        '429' => ['description' => 'Rate limited'],
                        '423' => ['description' => 'Account locked after too many failed attempts'],
                    ],
                ];

                if (! empty($metadata['parameters'])) {
                    $requiredParameters = $metadata['required_parameters'];

                    $entry[strtolower($method)]['parameters'] = array_map(
                        fn (string $name): array => $this->queryParameter($name, in_array($name, $requiredParameters, true)),
                        $metadata['parameters'],
                    );
                }
            }

            $paths[$path] = $entry;
        }

        return [
            'openapi' => '3.1.0',
            'info' => [
                'title' => 'Sistema de Caja Hospitalaria API',
                'version' => '1.0.0-rc.3',
                'description' => 'Same-origin API for the cashier / hospital billing app. Hosted on the LAN server, no internet required.',
            ],
            'servers' => [
                ['url' => 'http://IP-DEL-SERVIDOR:8000', 'description' => 'LAN server (production)'],
                ['url' => 'http://127.0.0.1:8000', 'description' => 'Local development'],
            ],
            'tags' => [
                ['name' => 'auth', 'description' => 'Session lifecycle and password change'],
                ['name' => 'system', 'description' => 'Health, status and CSP reports'],
                ['name' => 'invoices', 'description' => 'Invoice emission, listing and voiding'],
                ['name' => 'cash', 'description' => 'Cash session open / close / reconciliation'],
                ['name' => 'catalog', 'description' => 'Service and category management'],
                ['name' => 'backups', 'description' => 'Manual and scheduled backup log'],
                ['name' => 'reports', 'description' => 'Operational, financial and fiscal reports'],
                ['name' => 'settings', 'description' => 'Fiscal settings, sequences and branding'],
                ['name' => 'admin', 'description' => 'User and role administration'],
            ],
            'components' => [
                'securitySchemes' => [
                    'sanctum-session' => [
                        'type' => 'apiKey',
                        'in' => 'cookie',
                        'name' => 'XSRF-TOKEN / session cookie',
                    ],
                ],
            ],
            'paths' => $paths,
        ];
    }

    /**
     * @return array<string, mixed>
     */
    private function queryParameter(string $name, bool $required = false): array
    {
        return [
            'name' => $name,
            'in' => 'query',
            'required' => $required,
            'schema' => $this->queryParameterSchema($name),
        ];
    }

    /**
     * @return array<string, mixed>
     */
    private function queryParameterSchema(string $name): array
    {
        return match ($name) {
            'date', 'date_from', 'date_to' => ['type' => 'string', 'format' => 'date'],
            'month' => ['type' => 'string', 'pattern' => '^\d{4}-\d{2}$'],
            'cash_session_id', 'user_id', 'category_id', 'area_id' => ['type' => 'integer', 'minimum' => 1],
            'method' => ['type' => 'string', 'enum' => Payment::METHODS],
            'status' => ['type' => 'string', 'enum' => [
                Invoice::STATUS_ISSUED,
                Invoice::STATUS_PARTIAL,
                Invoice::STATUS_PAID,
                Invoice::STATUS_VOID,
            ]],
            default => ['type' => 'string'],
        };
    }
}
